from __future__ import annotations

import importlib
from typing import Any


_METRIC_MODULES_BY_NAME = {
    "check_gnome_favorite_apps": "basic_os",
    "is_utc_0": "basic_os",
    "check_text_enlarged": "basic_os",
    "check_moved_jpgs": "basic_os",
    "is_in_vm_clickboard": "basic_os",
    "is_expected_tabs": "chrome",
    "is_expected_bookmarks": "chrome",
    "compare_pdfs": "chrome",
    "compare_htmls": "chrome",
    "compare_archive": "chrome",
    "is_cookie_deleted": "chrome",
    "is_shortcut_on_desktop": "chrome",
    "check_font_size": "chrome",
    "check_enabled_experiments": "chrome",
    "check_history_deleted": "chrome",
    "is_expected_search_query": "chrome",
    "is_expected_active_tab": "chrome",
    "is_expected_url_pattern_match": "chrome",
    "is_added_to_steam_cart": "chrome",
    "is_expected_installed_extensions": "chrome",
    "compare_pdf_images": "chrome",
    "is_expected_active_tab_approximate": "chrome",
    "compare_font_names": "docs",
    "compare_subscript_contains": "docs",
    "has_page_numbers_in_footers": "docs",
    "compare_docx_lines": "docs",
    "evaluate_colored_words_in_tables": "docs",
    "check_highlighted_words": "docs",
    "evaluate_strike_through_last_paragraph": "docs",
    "evaluate_conversion": "docs",
    "evaluate_spacing": "docs",
    "check_italic_font_size_14": "docs",
    "evaluate_alignment": "docs",
    "get_unique_train_ids": "docs",
    "check_no_duplicates": "docs",
    "compare_init_lines": "docs",
    "find_default_font": "docs",
    "contains_page_break": "docs",
    "compare_docx_files": "docs",
    "compare_docx_tables": "docs",
    "compare_line_spacing": "docs",
    "compare_insert_equation": "docs",
    "compare_highlighted_text": "docs",
    "is_first_line_centered": "docs",
    "check_tabstops": "docs",
    "compare_contains_image": "docs",
    "compare_docx_files_and_ignore_new_lines": "docs",
    "compare_docx_images": "docs",
    "compare_image_text": "docs",
    "compare_references": "docs",
    "compare_unique_train_records": "docs",
    "check_csv": "general",
    "check_accessibility_tree": "general",
    "run_sqlite3": "general",
    "check_json": "general",
    "check_list": "general",
    "exact_match": "general",
    "match_in_list": "general",
    "is_in_list": "general",
    "fuzzy_match": "general",
    "check_include_exclude": "general",
    "check_direct_json_object": "general",
    "compare_time_in_speedtest_results": "general",
    "is_included_all_json_objects": "general",
    "is_gold_text_included_in_pdf": "general",
    "check_line_number": "general",
    "file_contains": "general",
    "compare_terminal_and_txt": "general",
    "fuzzy_place_math": "general",
    "compare_python_pure_text": "general",
    "diff_text_file": "general",
    "literal_match": "general",
    "check_structure_sim_resized": "gimp",
    "check_structure_sim_with_threshold": "gimp",
    "check_brightness_decrease_and_structure_sim": "gimp",
    "check_contrast_increase_and_structure_sim": "gimp",
    "check_saturation_increase_and_structure_sim": "gimp",
    "check_image_size": "gimp",
    "check_image_mirror": "gimp",
    "check_palette_and_structure_sim": "gimp",
    "check_textbox_on_leftside": "gimp",
    "check_green_background": "gimp",
    "check_file_exists_and_structure_sim": "gimp",
    "check_triangle_position": "gimp",
    "check_structure_sim": "gimp",
    "check_config_status": "gimp",
    "compare_image_list": "gimp",
    "increase_saturation": "gimp",
    "decrease_brightness": "gimp",
    "check_file_exists": "gimp",
    "compare_triangle_positions": "gimp",
    "check_sharper": "gimp",
    "check_image_file_size": "gimp",
    "check_libre_locale": "libreoffice",
    "compare_epub": "others",
    "check_mp3_meta": "others",
    "check_pdf_pages": "pdf",
    "check_presenter_console_disable": "slides",
    "check_image_stretch_and_center": "slides",
    "check_slide_numbers_color": "slides",
    "compare_pptx_files": "slides",
    "check_strikethrough": "slides",
    "check_slide_orientation_Portrait": "slides",
    "evaluate_presentation_fill_to_rgb_distance": "slides",
    "check_left_panel": "slides",
    "check_transition": "slides",
    "check_page_number_colors": "slides",
    "check_auto_saving_time": "slides",
    "compare_table": "table",
    "compare_csv": "table",
    "compare_conference_city_in_order": "table",
    "check_thunderbird_prefs": "thunderbird",
    "check_thunderbird_filter": "thunderbird",
    "check_thunderbird_folder": "thunderbird",
    "is_vlc_playing": "vlc",
    "is_vlc_recordings_folder": "vlc",
    "is_vlc_fullscreen": "vlc",
    "compare_images": "vlc",
    "compare_audios": "vlc",
    "compare_videos": "vlc",
    "check_qt_bgcone": "vlc",
    "check_one_instance_when_started_from_file": "vlc",
    "check_qt_minimal_view": "vlc",
    "check_qt_max_volume": "vlc",
    "check_qt_slider_colours": "vlc",
    "check_global_key_play_pause": "vlc",
    "check_play_and_exit": "vlc",
    "compare_text_file": "vscode",
    "compare_config": "vscode",
    "compare_answer": "vscode",
    "compare_result_files": "vscode",
    "is_extension_installed": "vscode",
    "check_json_settings": "vscode",
    "check_json_keybindings": "vscode",
    "check_python_file_by_test_suite": "vscode",
    "check_python_file_by_gold_file": "vscode",
    "check_html_background_image": "vscode",
    "compare_zip_files": "vscode",
}

__all__ = sorted([*_METRIC_MODULES_BY_NAME, "infeasible"])


def __getattr__(name: str) -> Any:
    module_name = _METRIC_MODULES_BY_NAME.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value


def infeasible():
    pass
